name: "Composer validate"

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    validate:
        name: "Composer validate"
        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.0"
        steps:
            -   uses: actions/checkout@v2

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "pcov"
                    php-version: "${{ matrix.php-version }}"
                    ini-values: memory_limit=-1

            -   name: Validate composer.json and composer.lock
                run: composer validate
